language: cpp
jobs:
  include:
    - name: "Ubuntu 16.04"
      os: linux
      dist: xenial
      compiler: g++
      addons:
       apt:
        packages: 
        - g++
        - libeigen3-dev
        - fakeroot
      script:
      - chmod +x debian/rules
      - fakeroot debian/rules clean
      - fakeroot debian/rules build
      after_success:
      - fakeroot debian/rules binary
    - name: "Doxygen"
      os: linux
      dist: focal
      branches:
       only:
       - master
      addons:
       apt:
        packages: 
        - doxygen
        - graphviz
      script:
      - doxygen Doxyfile
      deploy:
       provider: pages
       local_dir: html
       github_token: $GH_REPO_TOKEN
       on:
        branch: master

