language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
      compiler: g++
      addons:
       apt:
         packages: 
           - g++
           - libeigen3-dev
           - fakeroot

script:
     - chmod +x debian/rules
     - fakeroot debian/rules clean
     - fakeroot debian/rules build
after_success:
     - fakeroot debian/rules binary
