language: cpp
jobs:
  include:
    - name: "Ubuntu 16.04"
      os: linux
      dist: xenial
      sudo: true
      compiler: g++
      addons:
       apt:
         packages: 
           - g++
           - libeigen3-dev
           - fakeroot
      script:
      - chmod +x .build.sh
      - ./.build.sh
      after_success:
      - chmod +x .deploy.sh
      - ./.deploy.sh
    - name: "Doxygen"
      os: linux
      dist: focal
      sudo: false
      branches:
       only:
       - master
      addons:
       apt:
         packages: 
           - doxygen
           - graphviz
      script:
      - doxygen Doxyfile

